### ISSUE TITLE
Inclusion of potential new areas after splitting of sub-basins

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#11]
Consideration of 'new' assessment areas after splitting of sub-basins (Gulf of Finland, Bornholm Basin) when finally agreed including thresholds and shapefiles for exact area sizes are available:

1. Inclusion of new areas in assessment procedure, adaptation of input files (IndicatorUnits, UnitGridSize)
2. Assignment of grid cell sizes for spatial confidence: Western and Eastern Gulf of Finland (30K), Pommeranian Bay (30K), rest of Bornholm Basin 60K

**Comment by HjalteParner** [comment]
@jkaitaranta have the splitting of sub-basins (Gulf of Finland, Bornholm Basin) been agreed?, and if so can I get the thresholds and shapefiles for the new assessment units?

**Comment by jkaitaranta** [comment]
we have the open sea divisions agreed, including thresholds but are pending some final coastal unit changes so the final shapefiles are not ready yet. we should have shapefiles ready hopefully during next week.

**Comment by jkaitaranta** [comment]
@HjalteParner the updated 2022 assessment units for eutrophication are available here: https://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/c0d4c02f-4617-4636-94ef-8ea129094b52

**Comment by HjalteParner** [comment]
@jkaitaranta thanks, do you have the associated ET values for the different indicators where the assessment units have changed?

**Comment by HjalteParner** [comment]
@jkaitaranta it seems like the shapefile wont download from you service. Could you send it to me by email perhaps?

**Comment by jkaitaranta** [comment]
@HjalteParner will compile the ET values and add here. this is direct link to download: https://maps.helcom.fi/website/MADS/download/?id=c0d4c02f-4617-4636-94ef-8ea129094b52

**Comment by HjalteParner** [comment]
Done!
