### ISSUE TITLE
Inclusion of CyaBI in HEAT procedure

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#12]
Since cyanobacterial bloom index results are already normalized between 0-1, no EQR calculation is needed in HEAT for this indicator assuming that biomass and satellite data for CyaBI will be assessed and combined outside of HEAT (as this data is not available in ICES database). Only the normalization step to the equidistant scale of 0.2 width is required so that results are comparable with other indicator results (in line with different ways of reporting data into HEAT when this currently open issue is finalized). 
The following class boundaries should be used for the normalization step (based on the agreed thresholds, the remaining class boundaries have been calculated):

HELCOM ID | Assessment unit | Best | H/G | G/M | M/P | P/B | Worst

SEA-005 | Bay of Mecklenburg | 1 | 0.960 | 0.920 | 0.613 | 0.307 | 0
SEA-006 | Arkona Basin | 1 | 0.950 | 0.900 | 0.600 | 0.300 | 0
SEA-007 | Bornholm Basin | 1 | 0.935 | 0.870 | 0.580 | 0.290 | 0
SEA-008 | Gulf of Gdansk | 1 | 0.990 | 0.980 | 0.653 | 0.327 | 0
SEA-009 | Eastern Gotland Basin | 1 | 0.920 | 0.840 | 0.560 | 0.280 | 0
SEA-010 | Western Gotland Basin | 1 | 0.935 | 0.870 | 0.580 | 0.290 | 0
SEA-011 | Gulf of Riga | 1 | 0.950 | 0.900 | 0.600 | 0.300 | 0
SEA-012 | Northern Baltic   Proper | 1 | 0.885 | 0.770 | 0.513 | 0.257 | 0
SEA-013A | Gulf of Finland Western | 1 | 0.940 | 0.880 | 0.587 | 0.293 | 0
SEA-013B | Gulf of Finland Eastern | 1 | 0.952 | 0.905 | 0.603 | 0.302 | 0
SEA-015 | Bothnian Sea | 1 | 0.790 | 0.580 | 0.387 | 0.193 | 0

The confidence assessment of CyaBI still needs to be developed if not estimated and provided by the data submitter based on expert judgement. For in-situ biomass data the same confidence class boundaries as for chl-a in-situ data could be applied (for temporal and spatial confidence), if information on the number of observations is available. If the number of observations is also available for satellite data (CSA), a similar procedure might be possible as undertaken for chl-a satellite data using the number of 20K grid cells containing data, multiplied with the number of observation days during the year. Based on the number of observations and information on the standard deviation, the calculation of the accuracy would also be possible. When only already normalized and combined CyaBI assessment results (in-situ biomass and satellite CSA) are provided for integration with other indicators in HEAT, then confidence assessment would also need to be performed outside of HEAT.

**Comment by HjalteParner** [comment]
@birgitheyden which acceptable deviation have you used to calculate the class boundaries?

**Comment by birgitheyden** [comment]
@HjalteParner to my understanding we do not need to use acceptable deviation here and calculate EQR boundaries. CyaBI values are already on the EQR scale, using the agreed thresholds in the different assessment units and the EQR values only need to be tranferred to the equidistant EQRS scale. For doing this, the class boundaries above are the background and my thinking was that they can simply be defined as prerequisite in HEAT for the transformation step to final EQRS scale. This is linked to the issue of reporting assessment results in different ways into HEAT.

**Comment by HjalteParner** [comment]
@birgitheyden ok, I do not have any assessment unit called 13A and 13B and as such need to skip this unit.

**Comment by birgitheyden** [comment]
@HjalteParner this is already envisaged for the new shapefile Joni will send to you when finalized including splitting of Gulf of Finland in western and eastern part (13A and 13B) and Pomeranian Bay and rest of Bornholm Basin. For Gulf of Finland Western and Eastern new thresholds have already been agreed for CyaBI (that's why I have included them here). You could also start with the original Gulf of Finland sub-basin SEA-013 and the following class boundaries:  | 1 | 0.950 | 0.900 | 0.600 | 0.300 | 0 For Pomeranian Bay and the rest of Bornholm Basin adjusted thresholds are not available yet.

**Comment by HjalteParner** [comment]
@birgitheyden I guess this is done from my side. HEAT now support reporting of CyaBI as described above. Do you agree?

**Comment by birgitheyden** [comment]
***@***.***> @Hjalte Parner ***@***.***) I agree, this is included now.

 

Von: Hjalte Parner ***@***.***> 
Gesendet: Donnerstag, 7. April 2022 23:30
An: ices-tools-prod/HEAT ***@***.***>
Cc: birgitheyden ***@***.***>; Mention ***@***.***>
Betreff: Re: [ices-tools-prod/HEAT] Inclusion of CyaBI in HEAT procedure (Issue #12)

 

@birgitheyden <https://github.com/birgitheyden>  I guess this is done from my side. HEAT now support reporting of CyaBI as described above. Do you agree?
