### ISSUE TITLE
Inclusion of BQI in HEAT

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#13]
BQI inclusion needs to be done in two ways according to different thresholds and procedures used in the indicator assessment (details can be found in core indicator report). In the Gulf of Finland, Gulf of Riga, Eastern Gotland Basin, Bay of Mecklenburg and Kiel Bay the results are normalized to the scale 0-1, using 0.5 as threshold. In Aland Sea, Bothnian Sea, the Quark, Bothnian Bay, Northern Baltic Proper and Western Gotland Basin no normalization is applied and an EQR calculation can be performed (using 50% acceptable deviation) based on the ET and ES values provided. In areas with normalized values, no EQR calculation is necessary and only final normalization to the common scale of 0.2 width needs to be done. 
BQI thresholds and class boundaries to be used:

No EQR calculation, only transfer to equidistant scale of 0.2 width for the following sub-basins:
SEA-004 (Kiel Bay), SEA-005 (Bay of Mecklenburg), SEA-009 (Eastern Gotland Basin, SEA-011 (Gulf of Riga), SEA-013( Gulf of Finland)
using the same class boundaries for all sub-basins
| Best | H/G | G/M | M/P | P/B | Worst
| 1 | 0.75 | 0.5 | 0.33 | 0.17 | 0

EQR calculation, using class boundaries based on 50% acceptable deviation and subsequent normalization step for the following sub-basins:
HELCOM ID | Assessment unit | Best | G/M (ET value) |
SEA-010 | Western Gotland Basin | 6 |  4.0 |   
SEA-012 | Northern Baltic Proper | 6 |  4.0 |     
SEA-014 | Åland Sea | 6 |  4.0 |  
SEA-015 | Bothnian Sea | 6 | 4.0 |   
SEA-016 | The Quark | 2.25 | 1.5 |  
SEA-017 | Bothnian Bay | 2.25 | 1.5 |    

No agreed thresholds and no BQI assessment for HOLAS III in Gdansk Basin, Bornholm Basin, Arkona Basin, Great Belt, Kattegat, The Sound.

BQI confidence estimates need to be provided by data submitter/indicator leads, as these cannot be calculated in HEAT without the necessary detailed information (number of observations, spatial coverage etc.). For HOLAS II, confidence estimates were used based on expert judgement.
Since it is not clear in which areas the BQI will actually be used for the eutrophication assessment in HOLAS III (in HOLAS II only in the Gulf of Riga, Aland Sea, Bothnian Sea, The Quark, Bothnian Bay), it might be helpful to discuss this with Henrik Nygard and Vivi first.

**Comment by HjalteParner** [comment]
@birgitheyden I guess this is done from my side. HEAT now support reporting of BQI as described above. Do you agree?

**Comment by birgitheyden** [comment]
***@***.***> @Hjalte Parner ***@***.***) I agree that the inclusion of BQI is now included in HEAT and therefore can be moved to done. I noticed issues with reporting of different BQI assessment results and related class boundaries (for ES and EQR) in the configuration file, but perhaps it would be better to open a new issue for this? Otherwise, we could keep this as a reminder to revisit this in detail.

 

Von: Hjalte Parner ***@***.***> 
Gesendet: Donnerstag, 7. April 2022 23:28
An: ices-tools-prod/HEAT ***@***.***>
Cc: birgitheyden ***@***.***>; Mention ***@***.***>
Betreff: Re: [ices-tools-prod/HEAT] Inclusion of BQI in HEAT (Issue #13)

 

@birgitheyden <https://github.com/birgitheyden>  I guess this is done from my side. HEAT now support reporting of BQI as described above. Do you agree?

**Comment by HjalteParner** [comment]
@birgitheyden, yes please create a new issue for this if its still the case
