### ISSUE TITLE
Inclusion of oxygen debt in assessment procedure

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#14]
Oxygen debt script and assessment results need to be linked to the calculation procedure in HEAT for integrating results with other indicators, at least for available data from HOLAS II.
For oxygen debt an acceptable deviation of 50% should be used to calculate class boundaries for the EQR assessment. 

Oxygen debt thresholds (ET values):

HELCOM ID | Assessment unit | G/M (ET value)
SEA-007 | Bornholm Basin  | 6.37
SEA-008 | Gulf of Gdansk | 8.66
SEA-009 | Eastern Gotland Basin 8.66
SEA-010 | Western Gotland Basin | 8.66
SEA-012 | Northern Baltic   Proper | 8.66
SEA-013 | Gulf of Finland | 8.66

A solution still needs to be found to define the confidence classes according to the calculation procedure of the indicator and the number of (modelled) data used for this assessment. In a first approach, the class boundaries of chlorophyll could be used. It needs to be clarified whether a similar grid approach with 20K cells as for chlorophyll could be used for the modeled oxygen data (possibly to be discussed with Indicator Lead (EST)).

**Comment by jkaitaranta** [comment]
Related to oxygen debt, @HjalteParner the nitrogen input from 1995-2019 (as available now) in csv is attached here for encorporating to HOLAS3 (taken from core nutrient input indicator
[HOLAS3_OxyDebt_Nitrogen_1995_2019.csv](https://github.com/ices-tools-prod/HEAT/files/8197606/HOLAS3_OxyDebt_Nitrogen_1995_2019.csv)
)

**Comment by HjalteParner** [comment]
@jkaitaranta sorry for the long response time. I have now finally had a look at the values to make the update. Doing so I noticed that the new overlapping values aren't the same as previous. Is there an issue? Or should I just replace the values used in HOLAS II?

**Comment by jkaitaranta** [comment]
The reason is that some corrections are applied later on to the N input values. I would keep the latest values and delete old HOLAS II ones.

**Comment by HjalteParner** [comment]
Oxygen debt have now been refractured to being able to calculate the indicator for both HOLAS II and HOLAS III assessment period and the result have been added to the default configuration file and as such included in the assessment
