### ISSUE TITLE
Inclusion of near-bottom oxygen minima indicator for test assessments

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#15]
To include the oxygen minima assessment concept, several important basics need to be defined for the assessment season, maximum depth above sea floor, buffers around stations for pooling of stations with slightly different coordinates and aggregation/integration rules. Key points of oxygen minima indicator concept are also included in document attached.

Steps for implementation in HEAT:

1. Use oxygen data in assessment season: July-November (in the Western Baltic), July-Sept (Bothnian Bay, Bothnian Sea, The Quark)
2. Deepest sample from each observation, maximum distance of 4m above sea floor (information on bottom depth from EMODnet needed where missing)
3. Use buffer to aggregate stations into time-series (3x3 km)
4. Exclude individual measurements (less than 3 single observations in the entire assessment period)
5. Apply rule for classification of stations according to seasonally stratified or well-mixed conditions and related different thresholds (bottom depth <15 m: well-mixed 6 mg l-1; >15 m: seasonally stratified 4 mg l-1), acceptable deviation to be used: 50%
6. Apply rule for classification of stations according to repeated or occasional sampling (for subsequent weighted approach in spatial integration): Frequent sampling (defined as stations with several samplings per season and data in four or more years of 6-year period), count 3; Sampling frequency less than defined for frequent sampling, count 1
7. Determine seasonal minimum per station and year
8. Median of seasonal minima per station in assessment period 
9. Apply threshold per station to result in GES or non-GES
10. Apply weighting of station results for integration to final assessment result (majority principle based on classification of stations/weighting (count 3 or 1))

[Oxygen-minima-indicator-for-HELCOM-HEAT-implementation-20210914.docx](https://github.com/ices-tools-prod/HEAT/files/7981851/Oxygen-minima-indicator-for-HELCOM-HEAT-implementation-20210914.docx)

**Comment by HjalteParner** [comment]
@birgitheyden since this indicator now seem to be produced elsewhere and reported directly into HEAT, I guess this task can be closed?

**Comment by birgitheyden** [comment]
@HjalteParner Yes, this is correct and the task can be closed, at least for HOLAS III.
