### ISSUE TITLE
Check reporting of different BQI assessment results as ES or EQR

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#19]
There are issues with reporting of different BQI assessment results and related class boundaries (as ES or EQR value) in the configuration file, e.g. for unit 11 (Gulf of Riga) the assessment result of 0.55 is included in the IndicatorUnitsResults data sheet in the configuration file as ES value, but is in fact an EQR value (in contrast to the other BQI assessment results in units 14, 15, 16 and 17). This needs to be checked to ensure correct processing of the data.

**Comment by HjalteParner** [comment]
@birgitheyden I have now simply moved the indicator unit result for unit 11 from ES to EQR in the configuration file which should make the correct assessment for BQI. Please confirm this is correct and gives in the expected result.

**Comment by HjalteParner** [comment]
Done
