### ISSUE TITLE
Chlorophyll a FerryBox (FB) indicator?

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/HEAT#20]
SYKE has now submitted chlorophyll a ferry box data at a resolution of approximately 20 seconds for the period 2015-2020. These have been uploaded to the oceanographic database and is availeble for download as the oceanographic pump dataset at https://data.ices.dk.

The question is how to proceed.

In HOLAS II a separete chlorophyll a FB indicator was calculated from reported 20K grid aggregated results. However the 20K grids are not used anymore in HOLAS III.

I suggest one of two solutions for HOLAS III:

1) Calculate a dedicated chlorophyll a FB indicator directly calculated from data within all data withing the assessment units and then create the confidense assessment based on the HOLAS III 10K, 30K and 60K grids which are used by all the other in-situ indicators as well.

2) Do not calculate a separate chlorophyll a FB indicator as given in 1) but instead included the chlorophyll a values from ferrybox in the in-situ chlorophyll a indicator.

What do you recon will be the best approach?

**Comment by jkaitaranta** [comment]
The 1. solution would be preferred and aligned with the HOLAS2 procedure. However, the FB data would have to be aggregated to 20K grid for the spatial weighting process applied in chl-a indicator. Therefore the 20k grids are needed and have to be re-tagged to new HELCOM 2022 Level 4 open sea subbasin.

**Comment by HjalteParner** [comment]
The chlorophyll a ferry box indicator have been done using option 1.
