### ISSUE TITLE
Chlorophyll a Satellite (EO) indicator?

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/HEAT#21]
SYKE has now submitted chlorophyll a satellite indicator results with a reference to the HOLAS II 20K grids ids.

However in HOLAS III we are not using these 20K grids anymore and the ids cannot be aligned with the assessment units, as some assessment units have been split.

The question is how to proceed.

I suggest one of two solutions for HOLAS III:

1) The 20K grids (ids) are somehow mapped to the HOLAS III assessment units and then the confidense assessessment is skipped. I guess this mapping can be done both at SYKE, which then should resubmit the indicator results as HOLAS III assessment unit results or HEAT we could make a script in HEAT which will produce the final results. However in the latter case I will need some advise.

2) 'Raw' chlorophyll a satellite data are being made availeble and HEAT calculate the chlorophyl a satellite indicator directly by aggregating all data withing the assessment units and then create the confidense assessment based on the HOLAS III 10K, 30K and 60K grids which are used by all the other in-situ indicators as well.

What do you recon will be the best approach?

**Comment by jkaitaranta** [comment]
Solution 1. would be the preferred one for now in HOLAS3. The 20k grid is needed to be mapped for updated HELCOM 2022 Assessment units.

**Comment by HjalteParner** [comment]
The satellite indicator have now been implented using the HOLAS II 20K grid approaced based on a mapping from the HOLAS II 20K grids to the HOLAS III assessment units created by the HELCOM secretariat. No confidence assessment is as such carried out.
