### ISSUE TITLE
Adjustment of oxygen debt to digest the new input data format 

### ISSUE THREAD

**Issue by jkaitaranta** [ices-tools-dev/HEAT#23]
For the HOLAS3 HEAT run, and in current HEAT setup, the oxygen debt indicator needs to be run separately. The needed adjustment to for the script to digest the new input data format should be applied. This would make it possible to get the indicator results and input to HEAT integration.

**Comment by HjalteParner** [comment]
This task already describe in https://github.com/ices-tools-prod/HEAT/issues/14
