### ISSUE TITLE
Time series of ES values to be included in HEAT outputs

### ISSUE THREAD

**Issue by jkaitaranta** [ices-tools-dev/HEAT#25]
For the indicator reports, the time series graphs was produced manually for HOLAS2. It would be needed in HEAT to have pre-assessment period ES values per subbasin. In HOLAS3 configuration it would be 1970-2015. Desired output would be Mean ES per subbasin for each indicator that utilzise in-situ data.

**Comment by HjalteParner** [comment]
@jkaitaranta I have now added the option to choose the assessment period 1877-9999 which when run will produced the annual estimates for each indicator. I guess this should allow you to make your time series.
