### ISSUE TITLE
CPHL_EO spatial confidence to be set to High

### ISSUE THREAD

**Issue by jkaitaranta** [ices-tools-dev/HEAT#28]
Currently the CPHL indicator data type EO spatial confidence is not available. For now, the EO data type spatial confidence should be "hardcoded" to HEAT script to be "High" for all open sea subbasins (except the Sound where there is no CPHL_EO EQRS) to enable calculating integrated confidende for CPHL all data types as well as criteria 2 and overall assessment confidence.

**Comment by HjalteParner** [comment]
@jkaitaranta I have as requested now included the option to hardcode the GTC, STC and or SSC within the configuration file in the indicator unit results sheet and have updated the default configuration file with SSC = 100 (high) for CPHL_EO for all assessment units.

However above doesn't resolve the issue that when confidence is missing from one indicator in one assessment unit, then the result will still be missing both in the criteria and the overall assessment. I could in principle ignore missing values all over but are unsure if this is indeed the right approach (i.e. claiming unknown translate into ignore) and what the group wants?

**Comment by jkaitaranta** [comment]
Thanks. Please adjust the script so that it ignores missing values for now.

**Comment by HjalteParner** [comment]
Done, missing values are being ingnored
