### ISSUE TITLE
HEAT test assessment 2019 - comparison of ER and EQR

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#3]
Results of the review:
EQR values > 1: only 4 values for chl-a (3 in Kattegat, 1 in Kiel Bay) due to best values higher than ES
Scaled EQR values > 1: with the exception of the chl-a values above, this is probably due to an error in the formula for normalization of EQRs to scaled EQRs in the highest class: instead of +(MinNorm) the MaxNorm value was used resulting in too high scaled EQR based on the following formula:
EQRNorm = (EQRIndex - MinIndex)*(MaxNorm-MinNorm)/(MaxIndex-MinIndex)+(MinNorm). Example of TN in SEA-002: EQR 0.89, scaled EQR in workspace 1.09, but should also be 0.89 for scaled EQR result. Further cases: DIP SEA-017, TP SEA-002, chl-a (eo) SEA-002 and SEA-006, Secchi SEA-001.
For all other classes the scaling is correct.
One questionable value for Secchi in SEA-017: the EQR value of 0.55 should result in 0.20 for scaled EQR, but in the workspace the value is 0.42, please check.

**Comment by birgitheyden** [comment]
Addition to the review of the HEAT test assessment:
Concerning the display of different classification results (map view), there should be no difference between the EQR classification (based on indicator-specific class boundaries due to different acceptable deviations) and the scaled EQR classification (based on scaled classes of equidistant 0.2 width). This is probably due to the same scaled classification used for both values. This is kind of misleading, because it suggests differences where none exist. The view of the results should be related to the different underlying boundaries.

**Comment by HjalteParner** [comment]
Regarding Scaled EQR > 1 except CHLA I had indeed used the MaxNorm instead of the MinNorm value. This has now been corrected. However FYI I have used 1 for both MaxNorm and MaxIndex when EQR > EQR_HG. Overall the formula I have used to calculate EQRS is:

WHEN EQR <= EQR_PB THEN EQRS = (EQR - 0) * (0.2 - 0) / (EQR_PB - 0) + 0
WHEN EQR <= EQR_MP THEN EQRS = (EQR - EQR_PB) * (0.4 - 0.2) / (EQR_MP - EQR_PB) + 0.2
WHEN EQR <= EQR_GM THEN EQRS = (EQR - EQR_MP) * (0.6 - 0.4) / (EQR_GM - EQR_MP) + 0.4 
WHEN EQR <= EQR_HG THEN EQRS = (EQR - EQR_GM) * (0.8 - 0.6) / (EQR_HG - EQR_GM) + 0.6 
WHEN EQR > EQR_HG THEN EQRS = (EQR - EQR_HG) * (1 - 0.8) / (1 - EQR_HG) + 0.8

Let me know if this isn't how you want it calculated.

**Comment by HjalteParner** [comment]
Regarding Secchi depth in SEA-017 then AcDev is set to 33% which is different from SEA-002/0016 having an AcDev of 25% and SEA-001 having an AcDev of 24%. An AcDev of 33% result in the classification boundaries of 0.81/0.67/0.53/0.39 and with an EQR value of 0.55 result in an ERQS of 0.42 accordingly.

Let me know if I have misunderstood something.

**Comment by HjalteParner** [comment]
Regarding the display of EQR and EQRS in the map view, I have used the same equidistant 0.2 width scale for both. However I can understand why that's not desirable and will as such remove the EQR map view now as a dynamic scale isn't strait forward to implement and the results will (as you point out) be the same anyhow.

**Comment by birgitheyden** [comment]
The formula for scaled EQRs is now exactly the same as the one used in the previous test assessments for IN-Eutrophication and I also used 1 for both MaxNorm and MaxIndex. Regarding the Secchi depth result you are right and the EQRS is 0.42 due to the different acceptable deviation.
It' a good idea to remove the confusing EQR map view. So we can compare the final results of ER and EQRS directly and switch between the different views.
