### ISSUE TITLE
Possible ways to report indicator result into HEAT

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/HEAT#5]
1. ET, ACDEV = ES, BEST, EQR, EQR_HG, EQR_GM, EQR_MP, EQR_PB, EQRS calulated from data report to ICES database.
2. ET, ES, ACDEV = BEST, EQR, EQR_HG, EQR_GM, EQR_MP, EQR_PB, EQRS calulated from reported ES (Oxygen Debt)
3. EQR, ACDEV = EQR_HG, EQR_GM, EQR_MP, EQR_PB, EQRS calulated from reported EQR and ACDEV (BQI)
4. EQR, EQR_HG, EQR_GM, EQR_MP, EQR_PB = EQRS calulated from reported EQR, EQR_HG, EQR_GM, EQR_MP, EQR_PB (CyaCSA, CyaBM)
5. EQRS = used directly (Biological indicators of WFD results)

The higher option will overrule lower options

**Comment by HjalteParner** [comment]
@birgitheyden I have runned into an issue implementing multiple ways to report indicator unit results into HEAT and I'm not sure how to solve this as it stands.

Currently indicator unit assessment period results are calculated based on the mean annual ES result i.e. the assessment EQR and EQRS result are calculated from the mean annual ES result.

When allowed to report the annual result as EQR or directly as EQRS then it won't be possible to calculate the assessment period result based on the annual ES means anymore, and unfortunately the mean annual EQR or EQRS won't produced a comparable result.

Any ideas how to solve this issue?

**Comment by HjalteParner** [comment]
@birgitheyden one possible solution (the only solution I at least can see) to this issue would be to always based the assessment period indicator unit result on the mean annual EQRS result instead of the current mean annual ES result. 

However this is a fundemental change from the current procedure but this change would enable any reporting senario on either annual indicator unit result or assessment period indicator unit result.

**Comment by birgitheyden** [comment]
@HjalteParner My understanding was that annual ES, EQR and EQRS values are averaged in the same way for the entire assessment period and thus provide comparable results. Then it would not be decisive whether annual ES, EQR or EQRS values are used for the averaging of the entire period. Your proposal to base the assessment on mean annual EQRS values would solve this issue anyway, but in principle it would be good to apply a consistent calculation for ES, EQR and EQRS values. 

If we include EQR and EQRS values reported for different indicators in the configuration file (e.g. in indicator units as additional columns or as a separate data sheet), a condition rule could be linked to it in the script, I suppose. If EQR or EQRS values are present in the configuration file, then the associated calculation should be applied (as already defined in options/levels 1-5 above). Depending on whether besides EQR values either the accepted deviation or directly class boundaries are reported, the calculation differs (3. or 4.). If no EQR or EQRS values are reported, then the calculation is done as usual. In this way, the concept that the higher level overrules the lower level would be applied as planned.

**Comment by HjalteParner** [comment]
Done!
