### ISSUE TITLE
Adjustment of confidence categories for combined confidence results according to HOLAS II

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#6]
Confidence categories | Scores (as used in the eutrophication assessment of HOLAS II, should be the same for HOLAS III, adjust categories to these boundaries)

High | ≥ 75
Moderate | 50-74
Low | < 50

Confidence categories | Scores (as used in the biodiversity assessment of HOLAS II, originally proposed to be included in HEAT to harmonize assessments)

High | > 75
Moderate | 50-75
Low | < 50

**Comment by HjalteParner** [comment]
Done

**Comment by HjalteParner** [comment]
@birgitheyden is it correctly understood that HEAT should use High >= 75 while COMPEAT uses High > 75?

**Comment by birgitheyden** [comment]
@HjalteParner, it should be used for both assessments of HEAT and COMPEAT to harmonize as much as possible. We have to accept then that it does not fit exactly with BEAT, but the higher priority should be the consistency with the eutrophication assessment and the use of the same class boundaries as done in HOLAS II.
