### ISSUE TITLE
Inclusion of confidence maps in output files of HEAT

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#7]
Inclusion of confidence maps as output files in the HEAT procedure for temporal (TC), spatial (SC) and accuracy (ACC) confidence aspects separately, and also for overall confidence result on indicator, criteria and overall assessment level.

Examples of confidence maps from HOLAS II can be found in BSEP 156 Eutrophication Assessment (https://helcom.fi/wp-content/uploads/2019/12/BSEP156.pdf) on pages 16-19.

**Comment by HjalteParner** [comment]
@birgitheyden I will need the exact color definitions to be used for the confidence maps. I can BTW see from the report that also the color definitions from the status assessment seems to be different from the one used in my maps. I will send Joni an email for this.

**Comment by HjalteParner** [comment]
Done
