### ISSUE TITLE
Adaptation of grid cell sizes for spatial confidence 

### ISSUE THREAD

**Issue by birgitheyden** [ices-tools-dev/HEAT#8]
Suggestion to use 60K grid cells in larger sub-basins (marked in yellow in the table) in addition to 30K to result in a more consistent number of grids per area.

Suggested grid cells sizes in the different sub-basins:
![grafik](https://user-images.githubusercontent.com/49403960/120670784-0c43bd00-c491-11eb-9f85-5c7c55aadd8e.png)

Consideration of 'new' assessment areas after splitting of sub-basins (Gulf of Finland, Bornholm Basin) when finally agreed and shapefiles for exact area sizes are available:
Western and Eastern Gulf of Finland (30K)
Pommeranian Bay (30K), rest of Bornholm Basin 60K

**Comment by HjalteParner** [comment]
Done
