### ISSUE TITLE
Color definitions for eutrophication status and confidence assessment maps

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/HEAT#9]
In https://helcom.fi/wp-content/uploads/2019/12/BSEP156.pdf ex. page 16 the color scheme used for both the status and confidence assessment maps seems to differ from the current ones used in the HEAT.

EQRS_Class_colors <- c("#3BB300", "#99FF66", "#FFCABF", "#FF8066", "#FF0000")
EQRS_Class_limits <- c("High", "Good", "Moderate", "Poor", "Bad")
EQRS_Class_labels <- c(">= 0.8 - 1.0 (High)", ">= 0.6 - 0.8 (Good)", ">= 0.4 - 0.6 (Moderate)", ">= 0.2 - 0.4 (Poor)", ">= 0.0 - 0.2 (Bad)")

C_Class_colors <- c("#3BB300", "#FFCABF", "#FF0000")
C_Class_limits <- c("High", "Moderate", "Low")
C_Class_labels <- c(">= 75 % (High)", "50 - 74 % (Moderate)", "< 50 % (Low)")

I would like the exact color schemes to be used in HOLAS III which possible will be the same as for the HOLAS II report linked to?

**Comment by jkaitaranta** [comment]
Hi,

Colour codes used in HOLAS 2 publication. As far as we know these will be used in 3 but might still change in the process:  

ER, 5-scale (RGB colour code: R, G, B)
< 0.5 (119, 184, 143)
0.5-1 (186, 215, 194)
1-1.5 (235, 205, 197)
1.5-2 (216, 161, 151)
> 2 (199, 122, 112)

ConfidenceHigh (252, 231, 218)
ConfidenceModerate (245, 183, 142)
ConfidenceLow (204, 100, 23)

ER, 2-scale, used for indicator in HELCOM map and data service (R, G, B)
< 1 (98, 141, 126)
> 1 (162, 88, 95)

**Comment by HjalteParner** [comment]
Done
